name: Create published=true pull request
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: korosuke613/zenn-metadata-updater-action@v0.1.1
        with:
          published: true
          force-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
